# Generated by Django 5.2.17 on 2026-09-25 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodymetrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_weights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bodyweight',
            index=models.Index(fields=['user', 'date'], name='bodymetrics_user_id_007c5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bodyweight',
            unique_together={('user', 'date')},
        ),
    ]
