# Generated by Django 5.2.17 on 2026-09-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodymetrics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyweight',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyweight',
            name='photo_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
