import { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { Dumbbell, Home, Plus, Scale, Search, UserRound, Save } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:8000";
const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;
declare global { interface Window { google?: { accounts: { id: { initialize: (options: { client_id: string; callback: (response: { credential: string }) => void }) => void; renderButton: (element: HTMLElement, options: Record<string, string>) => void } } } } }
export async function api(path: string, options: RequestInit = {}) {
  const method = options.method || "GET"; let token: string | undefined;
  if (method !== "GET") { const csrfResponse = await fetch(`${API}/csrf/`, { credentials: "include" }); const csrfData = await csrfResponse.json(); token = csrfData.csrfToken; }
  const response = await fetch(`${API}${path}`, { credentials: "include", headers: { "Content-Type": "application/json", ...(token ? { "X-CSRFToken": token } : {}) }, ...options });
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || "No se pudo completar la operación");
  return response.status === 204 ? null : response.json();
}
export function Login() { const navigate = useNavigate(); const [error, setError] = useState(""); const googleButton = useRef<HTMLDivElement>(null); const submit = () => void api("/api/auth/dev_login/", { method: "POST", body: JSON.stringify({ email: "demo@dynamo.local" }) }).then(() => navigate("/dashboard")).catch((e: Error) => setError(e.message)); useEffect(() => { if (!GOOGLE_CLIENT_ID || !googleButton.current) return; const render = () => { if (!window.google || !googleButton.current) return; window.google.accounts.id.initialize({ client_id: GOOGLE_CLIENT_ID, callback: (response) => { void api("/api/auth/google/", { method: "POST", body: JSON.stringify({ credential: response.credential }) }).then(() => navigate("/dashboard")).catch((e: Error) => setError(e.message)); } }); window.google.accounts.id.renderButton(googleButton.current, { theme: "filled_blue", size: "large", width: "320" }); }; if (window.google) render(); else { const script = document.createElement("script"); script.src = "https://accounts.google.com/gsi/client"; script.async = true; script.onload = render; script.onerror = () => setError("No se pudo cargar Google Identity Services."); document.head.appendChild(script); } }, [navigate]); return <div className="auth"><div className="logo">D</div><h1>Dynamo</h1><p>Entrená con intención. Medí tu progreso.</p>{GOOGLE_CLIENT_ID ? <div ref={googleButton} className="google-button" /> : null}{import.meta.env.DEV && import.meta.env.MODE === "test" && <button className="primary wide" onClick={submit}>Continuar en modo desarrollo</button>}{error && <div className="error">{error}</div>}</div>; }
export function ProtectedRoute({ children }: { children: React.ReactNode }) { const [user, setUser] = useState<unknown>(); useEffect(() => { void api("/api/auth/me/").then(setUser).catch(() => setUser(null)); }, []); if (user === undefined) return <div className="loading">Cargando Dynamo…</div>; return user ? <>{children}</> : <Login />; }
function Layout({ children }: { children: React.ReactNode }) { return <><header><Link to="/dashboard" className="brand">Dynamo</Link><Link to="/profile" className="icon" aria-label="Mi perfil"><UserRound size={19} /></Link></header><main>{children}</main><nav className="bottom"><Link to="/dashboard"><Home size={19} />Inicio</Link><Link to="/exercises"><Search size={19} />Ejercicios</Link><Link to="/workouts/new"><Dumbbell size={19} />Entrenar</Link><Link to="/body-weight"><Scale size={19} />Peso</Link><Link to="/profile"><UserRound size={19} />Perfil</Link></nav></>; }
function Card({ label, value }: { label: string; value: React.ReactNode }) { return <div className="card"><small>{label}</small><strong>{value}</strong></div>; }
function Dashboard() { const [data, setData] = useState<any>(); useEffect(() => { void api("/api/dashboard/summary/").then(setData); }, []); return <><div className="title"><h2>Tu progreso</h2><Link className="primary" to="/workouts/new"><Plus size={17} /> Entrenar</Link></div><div className="grid cards"><Card label="Peso actual" value={data?.weight_current ? `${data.weight_current} kg` : "—"} /><Card label="Sesiones · 30 días" value={data?.workouts_30d ?? "—"} /><Card label="Volumen · 30 días" value={data ? `${Math.round(data.volume_30d)} kg` : "—"} /></div><section className="panel"><div className="section-head"><h3>Entrenamientos recientes</h3><Link to="/workouts">Ver todos</Link></div>{data?.recent_workouts?.length ? data.recent_workouts.map((w: any) => <Link className="row" to={`/workouts/${w.id}`} key={w.id}><span>{w.name}<small>{w.date}</small></span><strong>{Math.round(w.volume)} kg</strong></Link>) : <div className="empty">Todavía no hay entrenamientos.</div>}</section></>; }
function Exercises() { const [items, setItems] = useState<any[]>([]); const [query, setQuery] = useState(""); const load = () => void api(`/api/exercises/?search=${encodeURIComponent(query)}`).then((d) => setItems(d.results || d)); useEffect(load, []); return <><div className="title"><h2>Ejercicios</h2></div><div className="search"><Search size={18} /><input aria-label="Buscar ejercicio" placeholder="Buscar por nombre" value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} /></div><div className="exercise-grid">{items.map((item) => <Link className="exercise" to={`/progress/${item.id}`} key={item.id}>{item.image_1 ? <img src={item.image_1} alt="" /> : <div className="image-placeholder"><Dumbbell /></div>}<b>{item.name_es || item.name}</b>{item.name_es && item.name_es !== item.name && <small className="original-name">{item.name}</small>}<small>{item.primary_muscles?.join(", ")} · {item.equipment || "sin equipamiento"}</small></Link>)}</div>{!items.length && <div className="empty">No encontramos ejercicios.</div>}</>; }
function WorkoutRecorder() { const [workout, setWorkout] = useState<any>(() => JSON.parse(localStorage.getItem("dynamo.activeWorkout") || "null")); const [exercise, setExercise] = useState(""); const [weight, setWeight] = useState(""); const [reps, setReps] = useState(""); const [sets, setSets] = useState<any[]>([]); const start = () => void api("/api/workouts/", { method: "POST", body: JSON.stringify({ name: "Entrenamiento", started_at: new Date().toISOString() }) }).then((d) => { setWorkout(d); localStorage.setItem("dynamo.activeWorkout", JSON.stringify(d)); }); const add = () => void api(`/api/workouts/${workout.id}/exercises/`, { method: "POST", body: JSON.stringify({ exercise }) }).then((item) => api(`/api/workout-exercises/${item.id}/sets/`, { method: "POST", body: JSON.stringify({ reps: Number(reps), weight_kg: Number(weight), set_number: sets.length + 1, completed: true }) })).then((s) => { setSets((old) => [...old, s]); setWeight(""); setReps(""); }); const finish = () => void api(`/api/workouts/${workout.id}/finish/`, { method: "POST" }).then(() => { localStorage.removeItem("dynamo.activeWorkout"); setWorkout(null); }); return <><h2>Registrar entrenamiento</h2><div className="panel form">{!workout ? <button className="primary wide" onClick={start}>Iniciar entrenamiento</button> : <><label>ID del ejercicio<input value={exercise} onChange={(e) => setExercise(e.target.value)} placeholder="Pegá el UUID del ejercicio" /></label><div className="grid two"><label>Kg<input inputMode="decimal" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label>Reps<input inputMode="numeric" value={reps} onChange={(e) => setReps(e.target.value)} /></label></div><button className="primary wide" onClick={add}><Plus /> Agregar serie</button>{sets.map((s) => <div className="row" key={s.id}>{s.weight_kg} kg × {s.reps}</div>)}<button className="secondary wide" onClick={finish}>Finalizar entrenamiento</button></>}</div></>; }
function Workouts() { const [rows, setRows] = useState<any[]>([]); useEffect(() => { void api("/api/workouts/").then((d) => setRows(d.results || d)); }, []); return <><div className="title"><h2>Historial</h2><Link className="primary" to="/workouts/new"><Plus size={17} /></Link></div><section className="panel">{rows.length ? rows.map((w) => <Link className="row" to={`/workouts/${w.id}`} key={w.id}><span>{w.name}<small>{new Date(w.started_at).toLocaleDateString("es-AR")}</small></span><strong>{Math.round(w.volume)} kg</strong></Link>) : <div className="empty">Aún no registraste entrenamientos.</div>}</section></>; }
function WorkoutDetail() { const { id } = useParams(); const [data, setData] = useState<any>(); useEffect(() => { void api(`/api/workouts/${id}/`).then(setData); }, [id]); if (!data) return <div className="loading">Cargando…</div>; return <><h2>{data.name}</h2>{data.exercises.map((e: any) => <section className="panel" key={e.id}><h3>{e.exercise_name}</h3>{e.sets.map((s: any) => <div className="row" key={s.id}>Serie {s.set_number}<strong>{s.weight_kg} kg × {s.reps}</strong></div>)}</section>)}</>; }
function BodyWeight() { const [rows, setRows] = useState<any[]>([]); const [value, setValue] = useState(""); const load = () => void api("/api/body-weight/").then((d) => setRows(d.results || d)); useEffect(load, []); return <><h2>Peso corporal</h2><div className="panel form"><input inputMode="decimal" aria-label="Peso en kg" placeholder="Peso en kg" value={value} onChange={(e) => setValue(e.target.value)} /><button className="primary" onClick={() => void api("/api/body-weight/", { method: "POST", body: JSON.stringify({ date: new Date().toISOString().slice(0, 10), weight_kg: Number(value) }) }).then(load)}>Registrar peso</button></div>{rows.map((r) => <div className="row" key={r.id}>{r.date}<strong>{r.weight_kg} kg</strong></div>)}</>; }
function Progress() { const { id } = useParams(); const [data, setData] = useState<any>(); useEffect(() => { void api(`/api/progress/exercises/${id}/`).then(setData); }, [id]); if (!data) return <div className="loading">Cargando progreso…</div>; return <><h2>{data.exercise.name}</h2><div className="grid cards"><Card label="Mejor peso" value={`${data.summary.best_weight} kg`} /><Card label="1RM estimado" value={`${data.summary.best_1rm.toFixed(1)} kg`} /><Card label="Sesiones" value={data.summary.sessions} /></div><section className="panel chart-panel"><h3>Progreso por sesión</h3>{data.sessions.length ? <ResponsiveContainer width="100%" height={240}><LineChart data={data.sessions}><CartesianGrid stroke="#263244" strokeDasharray="3 3" /><XAxis dataKey="date" stroke="#8994a8" tick={{ fontSize: 11 }} /><YAxis stroke="#8994a8" tick={{ fontSize: 11 }} /><Tooltip contentStyle={{ background: "#121925", border: "1px solid #334155", color: "#e9edf5" }} /><Line type="monotone" dataKey="best_weight" name="Mejor peso" stroke="#9dfc7e" strokeWidth={3} dot={{ r: 4 }} /><Line type="monotone" dataKey="best_1rm" name="1RM estimado" stroke="#72a7ff" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer> : <div className="empty">Todavía no hay datos para graficar.</div>}</section><section className="panel">{data.sessions.map((s: any) => <div className="row" key={s.date}>{s.date}<strong>{s.best_weight} kg · {Math.round(s.volume)} kg</strong></div>)}</section></>; }
function Profile() { const [user, setUser] = useState<any>(); const [name, setName] = useState(""); const [avatar, setAvatar] = useState(""); const [message, setMessage] = useState(""); useEffect(() => { void api("/api/auth/me/").then((data) => { setUser(data); setName(data.name || ""); setAvatar(data.avatar_url || ""); }); }, []); if (!user) return <div className="loading">Cargando perfil…</div>; const save = () => void api("/api/auth/me/", { method: "PATCH", body: JSON.stringify({ name, avatar_url: avatar }) }).then((data) => { setUser(data); setMessage("Perfil actualizado"); }).catch((e: Error) => setMessage(e.message)); return <><div className="title"><h2>Mi perfil</h2></div><section className="panel profile"><div className="profile-head">{avatar ? <img className="profile-avatar" src={avatar} alt="" /> : <div className="profile-avatar avatar-fallback"><UserRound /></div>}<div><strong>{user.email}</strong><small>Cuenta conectada con Google</small></div></div><label>Nombre<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>URL del avatar<input type="url" value={avatar} onChange={(e) => setAvatar(e.target.value)} placeholder="https://..." /></label><button className="primary wide" onClick={save}><Save size={17} /> Guardar cambios</button>{message && <div className="hint">{message}</div>}</section></>; }
function App() { return <Routes><Route path="/login" element={<Login />} /><Route path="*" element={<ProtectedRoute><Layout><Routes><Route path="/dashboard" element={<Dashboard />} /><Route path="/exercises" element={<Exercises />} /><Route path="/workouts" element={<Workouts />} /><Route path="/workouts/:id" element={<WorkoutDetail />} /><Route path="/workouts/new" element={<WorkoutRecorder />} /><Route path="/body-weight" element={<BodyWeight />} /><Route path="/progress/:id" element={<Progress />} /><Route path="/profile" element={<Profile />} /><Route path="*" element={<Dashboard />} /></Routes></Layout></ProtectedRoute>} /></Routes>; }
const root = document.getElementById("root");
if (root) createRoot(root).render(<BrowserRouter><App /></BrowserRouter>);
