# Generated by Django 5.2 on 2026-09-30
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workouts", "0002_routines")]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="share_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
