# Generated by Django 5.2.17 on 2026-09-30 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_routine_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='source',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='workouts.routine'),
        ),
    ]
