# Generated by Django 5.2.17 on 2026-09-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('achievement', 'Logro'), ('follow', 'Seguidor'), ('message', 'Mensaje'), ('comment', 'Comentario'), ('like', 'Me gusta'), ('routine', 'Rutina')], max_length=20),
        ),
    ]
