# Generated by Django 5.2.17 on 2026-09-30 05:30

from django.db import migrations, models


def backfill(apps, schema_editor):
    from search_utils import normalize
    Model = apps.get_model("users", "User")
    rows = list(Model.objects.all())
    for row in rows:
        row.search_name = normalize(f"{row.name} {row.email.split('@')[0]}")
    Model.objects.bulk_update(rows, ["search_name"], batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
