# Generated by Django 5.2.17 on 2026-09-25 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('primary_muscles', models.JSONField(default=list)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=40)),
                ('instructions', models.JSONField(default=list)),
                ('image_1', models.URLField(blank=True)),
                ('image_2', models.URLField(blank=True)),
                ('source', models.CharField(default='Dynamo', max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
