# Generated by Django 5.2.17 on 2026-09-25 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='exercises_e_name_9bce89_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category', 'equipment'], name='exercises_e_categor_55076c_idx'),
        ),
    ]
