# Generated by Django 5.2.17 on 2026-09-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='force',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions_es',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
