# Generated by Django 5.2.17 on 2026-09-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='photo_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
