# Generated by Django 5.2.17 on 2026-09-30 05:30

from django.db import migrations, models


def backfill(apps, schema_editor):
    from search_utils import normalize
    Model = apps.get_model("exercises", "Exercise")
    rows = list(Model.objects.all())
    for row in rows:
        row.search_text = normalize(f"{row.name_es} {row.name}")
    Model.objects.bulk_update(rows, ["search_text"], batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_cloudinary_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='search_text',
            field=models.CharField(blank=True, editable=False, max_length=400),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
